import { E_NotificationType } from "../../generated/prisma";

export const notifications = [
  {
    title: 'Ticket Asignado a Técnico',
    toUserId: 3, 
    fromUserId: 11, 
    ticketId: 1,
    message: 'Tu ticket "Sin acceso a red local" ha sido asignado al técnico Oscar Ramírez.',
    isRead: false,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: 'Ticket Resuelto',
    toUserId: 4,
    fromUserId: 12, 
    ticketId: 2,
    message: 'Tu ticket "No se envían correos" ha sido resuelto por Jorge Alvarado.',
    isRead: true,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: 'Ticket Resuelto',
    toUserId: 5, 
    fromUserId: 13, 
    ticketId: 3,
    message: 'Tu ticket "Pantalla rota en laptop" ha sido resuelto por Sofía Martínez.',
    isRead: true,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {

    title: 'Ticket Asignado a Técnico',
    toUserId: 6,
    fromUserId: 14,
    ticketId: 4,
    message: 'Tu ticket "VPN no conecta" ha sido asignado al técnico Luis Castro.',
    isRead: false,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Cerrado',
    toUserId: 7,
    fromUserId: 15,
    ticketId: 5,
    message: 'Tu ticket "Antivirus detecta amenaza" ha sido cerrado por Andrea Vargas.',
    isRead: true,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Pendiente',
    toUserId: 8,
    fromUserId: null, 
    ticketId: 6,
    message: 'Tu ticket "No se reciben correos" aún está pendiente de asignación.',
    isRead: false,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Pendiente',
    toUserId: 9,
    fromUserId: null,
    ticketId: 7,
    message: 'Tu ticket "Acceso remoto bloqueado" aún está pendiente de asignación.',
    isRead: false,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Asignado a Técnico',
    toUserId: 10,
    fromUserId: 14,
    ticketId: 8,
    message: 'Tu ticket "Alerta de seguridad" ha sido asignado al técnico Luis Castro.',
    isRead: false,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Asignado a Técnico',
    toUserId: 3,
    fromUserId: 15,
    ticketId: 9,
    message: 'Tu ticket "Red interna inestable" ha sido asignado al técnico Andrea Vargas.',
    isRead: false,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket en Progreso',
    toUserId: 4,
    fromUserId: 11,
    ticketId: 10,
    message: 'Tu ticket "Teclado no responde" está en progreso con el técnico Oscar Ramírez.',
    isRead: false,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Resuelto',
    toUserId: 5,
    fromUserId: 12,
    ticketId: 11,
    message: 'Tu ticket "Correo duplicado" fue solucionado por Jorge Alvarado.',
    isRead: true,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Cerrado',
    toUserId: 6,
    fromUserId: 13,
    ticketId: 12,
    message: 'Tu ticket "VPN solucionada" fue cerrado por Sofía Martínez.',
    isRead: true,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    
    title: 'Ticket Cerrado',
    toUserId: 7,
    fromUserId: 14,
    ticketId: 13,
    message: 'Tu ticket "Amenaza eliminada" fue cerrado por Luis Castro.',
    isRead: true,
    type: E_NotificationType.TICKET_UPDATE,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
