import { E_TicketPriority } from "../../generated/prisma";
import { E_TicketStatus } from "../../generated/prisma";
import { E_AssignedMethod } from "../../generated/prisma";
export const tickets = [
  {
    //1
    userId: 3,
    technicianId: 1,
    ticketCategoryId: 1, // Redes internas → SLA Básico
    title: 'Sin acceso a red local',
    description: 'El equipo no detecta la red LAN del edificio',
    priority: E_TicketPriority.HIGH,
    status: E_TicketStatus.IN_PROGRESS,
    storyPoints: 4,
    aceptanceCriteria: 'El equipo debe conectarse a la red interna sin errores.',
    comments: 'Se revisó el cableado y configuración IP.',
    resolutionDays: 2,
    slaReply: 24,
    slaResolution: 72,
    replyAchieved: true,
    resolutionAchieved: null, // no está resuelto
    ticketValorationId: null, // no está cerrado
    assignedMethod: E_AssignedMethod.MANUAL,
    automaticTriageRuleId: null,
    assignedAt: new Date('2025-10-12T09:30:00'),
    closedAt: null,
    createdAt: new Date('2025-10-11T08:00:00'),
    updatedAt: new Date('2025-10-13T10:00:00')
  },
  {
    //2
    userId: 4,
    technicianId: 2,
    ticketCategoryId: 2, // Correo electrónico → SLA Estándar
    title: 'No se envían correos',
    description: 'Outlook muestra error al enviar mensajes',
    priority: E_TicketPriority.MEDIUM,
    status: E_TicketStatus.RESOLVED,
    storyPoints: 3,
    aceptanceCriteria: 'El usuario debe poder enviar correos sin errores.',
    comments: 'Se ajustó el servidor SMTP y se probó envío.',
    resolutionDays: 1,
    slaReply: 12,
    slaResolution: 48,
    replyAchieved: true,
    resolutionAchieved: true,
    ticketValorationId: null, // no está cerrado
    assignedMethod: E_AssignedMethod.AUTOMATIC,
    automaticTriageRuleId: 2,
    assignedAt: new Date('2025-09-28T10:00:00'),
    closedAt: null,
    createdAt: new Date('2025-09-27T09:00:00'),
    updatedAt: new Date('2025-09-29T11:00:00')
  },
  {
    //3
    userId: 5,
    technicianId: 3,
    ticketCategoryId: 3, // Hardware dañado → SLA Premium
    title: 'Pantalla rota en laptop',
    description: 'La pantalla está fisurada y no muestra imagen',
    priority: E_TicketPriority.HIGH,
    status: E_TicketStatus.CLOSED,
    storyPoints: 5,
    aceptanceCriteria: 'La pantalla debe estar funcional y sin daños físicos.',
    comments: 'Se reemplazó el panel y se probó el equipo.',
    resolutionDays: 1,
    slaReply: 4,
    slaResolution: 24,
    replyAchieved: true,
    resolutionAchieved: true,
    ticketValorationId: 1,
    assignedMethod: E_AssignedMethod.MANUAL,
    automaticTriageRuleId: null,
    assignedAt: new Date('2025-10-05T08:00:00'),
    closedAt: new Date('2025-10-07T14:00:00'),
    createdAt: new Date('2025-10-04T09:00:00'),
    updatedAt: new Date('2025-10-07T14:00:00')
  },
  {
    //4
    userId: 6,
    technicianId: 4,
    ticketCategoryId: 4, // Acceso remoto → SLA Crítico
    title: 'VPN no conecta',
    description: 'El cliente VPN muestra error de autenticación',
    priority: E_TicketPriority.HIGH,
    status: E_TicketStatus.ASSIGNED,
    storyPoints: 4,
    aceptanceCriteria: 'El usuario debe poder conectarse remotamente sin errores.',
    comments: 'Se revisó configuración y credenciales.',
    resolutionDays: 1,
    slaReply: 1,
    slaResolution: 8,
    replyAchieved: true,
    resolutionAchieved: null,
    ticketValorationId: null,
    assignedMethod: E_AssignedMethod.AUTOMATIC,
    automaticTriageRuleId: 4,
    assignedAt: new Date('2025-10-14T11:00:00'),
    closedAt: null,
    createdAt: new Date('2025-10-13T10:00:00'),
    updatedAt: new Date('2025-10-14T11:00:00')
  },
  {
    //5
    userId: 7,
    technicianId: 5,
    ticketCategoryId: 5, // Seguridad informática → SLA Flexible
    title: 'Antivirus detecta amenaza',
    description: 'Se detectó malware en el equipo del usuario',
    priority: E_TicketPriority.MEDIUM,
    status: E_TicketStatus.CLOSED,
    storyPoints: 3,
    aceptanceCriteria: 'El sistema debe estar libre de amenazas.',
    comments: 'Se eliminó el archivo malicioso y se actualizó el antivirus.',
    resolutionDays: 2,
    slaReply: 6,
    slaResolution: 36,
    replyAchieved: true,
    resolutionAchieved: true,
    ticketValorationId: 2,
    assignedMethod: E_AssignedMethod.MANUAL,
    automaticTriageRuleId: null,
    assignedAt: new Date('2025-09-30T09:00:00'),
    closedAt: new Date('2025-10-02T16:00:00'),
    createdAt: new Date('2025-09-29T08:00:00'),
    updatedAt: new Date('2025-10-02T16:00:00')
  },
  {
    //6
    userId: 8,
    technicianId: null,
    ticketCategoryId: 2,
    title: 'No se reciben correos',
    description: 'La bandeja de entrada no actualiza nuevos mensajes',
    priority: E_TicketPriority.MEDIUM,
    status: E_TicketStatus.PENDING,
    storyPoints: 2,
    aceptanceCriteria: 'El usuario debe recibir correos sin interrupciones.',
    comments: 'Pendiente de revisión de configuración IMAP.',
    resolutionDays: 1,
    slaReply: 12,
    slaResolution: 48,
    replyAchieved: false,
    resolutionAchieved: null,
    ticketValorationId: null,
    assignedMethod: null,
    automaticTriageRuleId: null,
    assignedAt: null,
    closedAt: null,
    createdAt: new Date('2025-10-08T09:00:00'),
    updatedAt: new Date('2025-10-08T09:00:00')
  },
  {
    //7
    userId: 9,
    technicianId: null,
    ticketCategoryId: 4,
    title: 'Acceso remoto bloqueado',
    description: 'No se puede conectar al servidor desde casa',
    priority: E_TicketPriority.HIGH,
    status: E_TicketStatus.PENDING,
    storyPoints: 3,
    aceptanceCriteria: 'El usuario debe acceder remotamente sin errores.',
    comments: 'Pendiente de revisión de firewall.',
    resolutionDays: 2,
    slaReply: 1,
    slaResolution: 8,
    replyAchieved: false,
    resolutionAchieved: null,
    ticketValorationId: null,
    assignedMethod: null,
    automaticTriageRuleId: 4,
    assignedAt: null,
    closedAt: null,
    createdAt: new Date('2025-10-09T10:00:00'),
    updatedAt: new Date('2025-10-09T10:00:00')
  },
  {
    //8
    userId: 10,
    technicianId: 4,
    ticketCategoryId: 5,
    title: 'Alerta de seguridad',
    description: 'El antivirus detecta actividad sospechosa',
    priority: E_TicketPriority.HIGH,
    status: E_TicketStatus.ASSIGNED,
    storyPoints: 4,
    aceptanceCriteria: 'El sistema debe estar libre de amenazas.',
    comments: 'Se está evaluando el archivo detectado.',
    resolutionDays: 2,
    slaReply: 6,
    slaResolution: 36,
    replyAchieved: true,
    resolutionAchieved: null,
    ticketValorationId: null,
    assignedMethod: E_AssignedMethod.MANUAL,
    automaticTriageRuleId: null,
    assignedAt: new Date('2025-10-10T11:00:00'),
    closedAt: null,
    createdAt: new Date('2025-10-09T09:00:00'),
    updatedAt: new Date('2025-10-10T11:00:00')
  },
  {
    //9
    userId: 3,
    technicianId: 5,
    ticketCategoryId: 1,
    title: 'Red interna inestable',
    description: 'La conexión LAN se cae intermitentemente',
    priority: E_TicketPriority.MEDIUM,
    status: E_TicketStatus.ASSIGNED,
    storyPoints: 3,
    aceptanceCriteria: 'La red debe mantenerse estable.',
    comments: 'Se revisan logs del switch.',
    resolutionDays: 2,
    slaReply: 24,
    slaResolution: 72,
    replyAchieved: true,
    resolutionAchieved: null,
    ticketValorationId: null,
    assignedMethod: E_AssignedMethod.AUTOMATIC,
    automaticTriageRuleId: 1,
    assignedAt: new Date('2025-10-11T10:00:00'),
    closedAt: null,
    createdAt: new Date('2025-10-10T08:00:00'),
    updatedAt: new Date('2025-10-11T10:00:00')
  },
  {
    //10
    userId: 4,
    technicianId: 1,
    ticketCategoryId: 3,
    title: 'Teclado no responde',
    description: 'El teclado deja de funcionar aleatoriamente',
    priority: E_TicketPriority.LOW,
    status: E_TicketStatus.IN_PROGRESS,
    storyPoints: 2,
    aceptanceCriteria: 'El teclado debe funcionar sin interrupciones.',
    comments: 'Se está probando con otro periférico.',
    resolutionDays: 1,
    slaReply: 4,
    slaResolution: 24,
    replyAchieved: true,
    resolutionAchieved: null,
    ticketValorationId: null,
    assignedMethod: E_AssignedMethod.MANUAL,
    automaticTriageRuleId: null,
    assignedAt: new Date('2025-10-12T09:00:00'),
    closedAt: null,
    createdAt: new Date('2025-10-11T08:00:00'),
    updatedAt: new Date('2025-10-13T10:00:00')
  },
  {
    //11
    userId: 5,
    technicianId: 2,
    ticketCategoryId: 2,
    title: 'Correo duplicado',
    description: 'Los correos se duplican en la bandeja de entrada',
    priority: E_TicketPriority.MEDIUM,
    status: E_TicketStatus.RESOLVED,
    storyPoints: 3,
    aceptanceCriteria: 'Los correos deben aparecer una sola vez.',
    comments: 'Se ajustó la sincronización IMAP.',
    resolutionDays: 1,
    slaReply: 12,
    slaResolution: 48,
    replyAchieved: true,
    resolutionAchieved: true,
    ticketValorationId: null,
    assignedMethod: E_AssignedMethod.AUTOMATIC,
    automaticTriageRuleId: 2,
    assignedAt: new Date('2025-10-13T10:00:00'),
    closedAt: null,
    createdAt: new Date('2025-10-12T09:00:00'),
    updatedAt: new Date('2025-10-14T11:00:00')
  },
  {
    //12
    userId: 6,
    technicianId: 3,
    ticketCategoryId: 4,
    title: 'VPN solucionada',
    description: 'Se resolvió el problema de conexión remota',
    priority: E_TicketPriority.HIGH,
    status: E_TicketStatus.CLOSED,
    storyPoints: 4,
    aceptanceCriteria: 'El usuario debe conectarse sin errores.',
    comments: 'Se actualizó el cliente VPN.',
    resolutionDays: 1,
    slaReply: 1,
    slaResolution: 8,
    replyAchieved: true,
    resolutionAchieved: true,
    ticketValorationId: 6,
    assignedMethod: E_AssignedMethod.AUTOMATIC,
    automaticTriageRuleId: 4,
    assignedAt: new Date('2025-10-14T08:00:00'),
    closedAt: new Date('2025-10-15T14:00:00'),
    createdAt: new Date('2025-10-13T09:00:00'),
    updatedAt: new Date('2025-10-15T14:00:00')
  },
  {
    //13
    userId: 7,
    technicianId: 4,
    ticketCategoryId: 5,
    title: 'Amenaza eliminada',
    description: 'Se eliminó el malware detectado por el antivirus',
    priority: E_TicketPriority.MEDIUM,
    status: E_TicketStatus.CLOSED,
    storyPoints: 3,
    aceptanceCriteria: 'El sistema debe estar libre de amenazas.',
    comments: 'Se aplicó limpieza completa.',
    resolutionDays: 2,
    slaReply: 6,
    slaResolution: 36,
    replyAchieved: true,
    resolutionAchieved: true,
    ticketValorationId: 7,
    assignedMethod: E_AssignedMethod.MANUAL,
    automaticTriageRuleId: null,
    assignedAt: new Date('2025-10-16T09:00:00'),
    closedAt: new Date('2025-10-18T15:00:00'),
    createdAt: new Date('2025-10-15T08:00:00'),
    updatedAt: new Date('2025-10-18T15:00:00')
  }
];


