import { E_Role } from "../../generated/prisma";

export const users = [
  {
    //1
    name: 'Oscar',
    lastName: 'Ramírez',
    email: 'oscar@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.ADMIN,
    profileImage: 'oscar-profile.jpg',
    genre: 'male',
    dob: new Date('1995-05-20'),
    cellphone: '84762042',
  },
  {
    //2
    name: 'Lucía',
    lastName: 'Gómez',
    email: 'lucia@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.ADMIN,
    profileImage: 'lucia-profile.jpg',
    genre: 'female',
    dob: new Date('1992-08-15'),
    cellphone: '88887777',
  },
  {
    //3
    name: 'Carlos',
    lastName: 'Méndez',
    email: 'carlos@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'carlos-profile.jpg',
    genre: 'male',
    dob: new Date('1990-01-10'),
    cellphone: '89998888',
  },
  {
    //4
    name: 'Ana',
    lastName: 'Jiménez',
    email: 'ana@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'ana-profile.jpg',
    genre: 'female',
    dob: new Date('1993-03-12'),
    cellphone: '87001122',
  },
  {
    //5
    name: 'Roberto',
    lastName: 'Salas',
    email: 'roberto@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'roberto-profile.jpg',
    genre: 'male',
    dob: new Date('1988-07-25'),
    cellphone: '88112233',
  },
  {
    //6
    name: 'Diego',
    lastName: 'Rojas',
    email: 'diego@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'diego-profile.jpg',
    genre: 'male',
    dob: new Date('1996-11-02'),
    cellphone: '88223344',
  },
  {
    //7
    name: 'Valeria',
    lastName: 'Campos',
    email: 'valeria@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'valeria-profile.jpg',
    genre: 'female',
    dob: new Date('1994-09-18'),
    cellphone: '88334455',
  },
  {
    //8
    name: 'Esteban',
    lastName: 'Morales',
    email: 'esteban@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'esteban-profile.jpg',
    genre: 'male',
    dob: new Date('1991-12-30'),
    cellphone: '88445566',
  },
  {
    //9
    name: 'Laura',
    lastName: 'Soto',
    email: 'laura@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'laura-profile.jpg',
    genre: 'female',
    dob: new Date('1997-04-05'),
    cellphone: '88556677',
  },
  {
    //10
    name: 'Fernando',
    lastName: 'León',
    email: 'fernando@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.USER,
    profileImage: 'fernando-profile.jpg',
    genre: 'male',
    dob: new Date('1989-06-22'),
    cellphone: '88667788',
  },
  {
    //11
    name: 'María',
    lastName: 'Fernández',
    email: 'maria@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.TECHNICIAN,
    profileImage: 'maria-profile.jpg',
    genre: 'female',
    dob: new Date('1993-02-14'),
    cellphone: '88778899',
  },
  {
    //12
    name: 'Jorge',
    lastName: 'Alvarado',
    email: 'jorge@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.TECHNICIAN,
    profileImage: 'jorge-profile.jpg',
    genre: 'male',
    dob: new Date('1990-08-09'),
    cellphone: '88990011',
  },
  {
    //13
    name: 'Sofía',
    lastName: 'Martínez',
    email: 'sofia@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.TECHNICIAN,
    profileImage: 'sofia-profile.jpg',
    genre: 'female',
    dob: new Date('1995-01-25'),
    cellphone: '88001122',
  },
  {
    //14
    name: 'Luis',
    lastName: 'Castro',
    email: 'luis@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.TECHNICIAN,
    profileImage: 'luis-profile.jpg',
    genre: 'male',
    dob: new Date('1987-10-11'),
    cellphone: '88112233',
  },
  {
    //15
    name: 'Andrea',
    lastName: 'Vargas',
    email: 'andrea@tech.com',
    password: '$2b$10$1BaQqXuZYNLDAC42PY5fN.ufSOKjApmjkaZrQUYf7ms71PaS1mASO',
    role: E_Role.TECHNICIAN,
    profileImage: 'andrea-profile.jpg',
    genre: 'female',
    dob: new Date('1998-07-07'),
    cellphone: '88223344',
  },
];

